// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using Stott.Optimizely.Csp.Entities;

namespace Stott.Optimizely.Csp.Migrations
{
    [DbContext(typeof(CspDataContext))]
    partial class CspDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Stott.Optimizely.Csp.Entities.CspSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReportOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspSettings");
                });

            modelBuilder.Entity("Stott.Optimizely.Csp.Entities.CspSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Directives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspSource");
                });

            modelBuilder.Entity("Stott.Optimizely.Csp.Entities.CspViolationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockedUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectiveDirective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referrer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Reported")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScriptSample")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViolatedDirective")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspViolationReport");
                });

            modelBuilder.Entity("Stott.Optimizely.Csp.Entities.SecurityHeaderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FrameOptions")
                        .HasColumnType("int");

                    b.Property<bool>("IsXContentTypeOptionsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsXXssProtectionEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("ReferrerPolicy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspSecurityHeaderSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
