// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stott.Security.Core.Entities;

#nullable disable

namespace Stott.Security.Core.Migrations
{
    [DbContext(typeof(CspDataContext))]
    partial class CspDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Stott.Security.Core.Entities.CspSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReportOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspSettings");
                });

            modelBuilder.Entity("Stott.Security.Core.Entities.CspSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Directives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspSource");
                });

            modelBuilder.Entity("Stott.Security.Core.Entities.CspViolationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockedUri")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Instances")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViolatedDirective")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BlockedUri", "ViolatedDirective" }, "idx_CspViolationSummary_LookUp");

                    b.ToTable("tbl_CspViolationSummary");
                });

            modelBuilder.Entity("Stott.Security.Core.Entities.SecurityHeaderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CrossOriginEmbedderPolicy")
                        .HasColumnType("int");

                    b.Property<int>("CrossOriginOpenerPolicy")
                        .HasColumnType("int");

                    b.Property<int>("CrossOriginResourcePolicy")
                        .HasColumnType("int");

                    b.Property<bool>("ForceHttpRedirect")
                        .HasColumnType("bit");

                    b.Property<int>("FrameOptions")
                        .HasColumnType("int");

                    b.Property<bool>("IsStrictTransportSecurityEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStrictTransportSecuritySubDomainsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("ReferrerPolicy")
                        .HasColumnType("int");

                    b.Property<int>("StrictTransportSecurityMaxAge")
                        .HasColumnType("int");

                    b.Property<int>("XContentTypeOptions")
                        .HasColumnType("int");

                    b.Property<int>("XssProtection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_CspSecurityHeaderSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
